version: "3"
services:
  tierjig_php_fpm:
    build: docker/php_fpm
    image: tierjig_php_fpm:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "php", "service": "tierjig_phpfpm"}]'
    volumes:
      - .:/var/www
    restart: always
  tierjig_php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - tierjig_php_fpm
    labels:
      com.datadoghq.ad.logs: '[{"source": "php", "service": "tierjig_php_fpm_debug"}]'
    volumes:
      - .:/var/www
    restart: always
  nginx:
    build: docker/nginx
    depends_on:
      - tierjig_php_fpm
      - tierjig_php_fpm_debug
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "tierjig_nginx"}]'
    volumes:
      - .:/var/www
    restart: always

